"""Section functions for P-11 reports (M-P11.2).

Each section is one function returning an HTML fragment. The
renderer composes a template's report by calling sections in the
order declared by the template's ``sections`` tuple, joining the
fragments inside the Jinja shell.

Reuses ``engine.verbal_summary.generate_verbal_summary`` so report
prose stays in lockstep with P-05's C7 surface.
"""

# M-P11.2
from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Callable

from engine.constants import TRAFFIC_LIGHT_THRESHOLDS
from engine.verbal_summary import generate_verbal_summary
from ui.components.p04_indicator_registry import ALL_INDICATOR_IDS
from ui.components.trend_record import (
    significance_text,
    slope_display,
    verdict_badge,
)
from ui.components.trend_svg import build_trend_svg


# ──────────────────────────────────────────────────────────────────
# Section dispatch
# ──────────────────────────────────────────────────────────────────

def get_section(section_key: str) -> Callable | None:
    """Map a template's section key to its render function."""
    return _SECTION_REGISTRY.get(section_key)


# ──────────────────────────────────────────────────────────────────
# Title page
# ──────────────────────────────────────────────────────────────────

def _render_title_page(state, sources) -> str:
    """First page — title, date, source count, scope summary."""
    today = datetime.now(timezone.utc)
    title_text = state.title.strip() if state.title else ""
    title = html.escape(title_text or "Untitled report")
    date_str = today.strftime("%d %B %Y")
    n_sources = len(sources)
    source_word = "source" if n_sources == 1 else "sources"
    return f"""
    <section>
      <h1>{title}</h1>
      <div class="meta-grid">
        <span class="meta-label">Report date</span><span>{date_str}</span>
        <span class="meta-label">Sources</span><span>{n_sources} {source_word}</span>
        <span class="meta-label">Generated by</span><span>GSCO Environmental Monitoring tool</span>
      </div>
    </section>
    """


# ──────────────────────────────────────────────────────────────────
# Executive summary
# ──────────────────────────────────────────────────────────────────

def _render_executive_summary(state, sources) -> str:
    """Short composite findings summary across all sources."""
    blocks = ["<section>", "<h2>Executive Summary</h2>"]
    notes_text = (state.notes or "").strip()
    if notes_text:
        blocks.append(f"<p>{html.escape(notes_text)}</p>")
    blocks.append(
        f"<p>This report covers {len(sources)} saved "
        f"{'analysis' if len(sources) == 1 else 'analyses'} "
        f"selected from the GSCO Environmental Monitoring tool.</p>"
    )

    # Per-source one-liner.
    blocks.append("<table>")
    blocks.append("<tr><th>Source</th><th>Type</th><th>Composite</th><th>Band</th></tr>")
    for src in sources:
        name = html.escape(src.get("name", "Untitled"))
        type_ = html.escape(src.get("type", "—"))
        composite = _composite_score(src)
        band, band_label = _band_for_score(composite)
        composite_str = f"{composite:.2f}" if composite is not None else "—"
        blocks.append(
            f"<tr><td>{name}</td><td>{type_}</td><td>{composite_str}</td>"
            f"<td><span class='pillar-chip {band}'>{band_label}</span></td></tr>"
        )
    blocks.append("</table>")
    blocks.append("</section>")
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Methodology
# ──────────────────────────────────────────────────────────────────

def _render_methodology(state, sources) -> str:
    """Standard methodology block, source-agnostic."""
    n_indicators_each = [_count_indicators_run(s) for s in sources]
    partial = [n for n in n_indicators_each if n is not None and n < 19]
    caveat = ""
    if partial:
        caveat = (
            "<div class='caveat'>"
            f"<strong>Partial coverage.</strong> {len(partial)} of "
            f"{len(sources)} sources in this report ran with fewer than "
            "the full 19 indicators. See per-source methodology notes "
            "below for details on what was screened."
            "</div>"
        )
    return f"""
    <section>
      <h2>Methodology</h2>
      <p>The GSCO Environmental Monitoring tool computes environmental
         screening across three pillars — Air Pollution, Greenhouse Gas
         Emissions, and Nature/Land — drawing on satellite earth-observation
         data via Google Earth Engine, scientific reference datasets, and
         emissions inventory products.</p>
      <p>Each pillar produces a 0–1 follow-up priority score. Bands:
         0.66+ = red (audit-first), 0.33–0.66 = amber (investigate),
         &lt; 0.33 = green (routine). Confidence is reported alongside
         each score and reflects coverage, retrieval quality, and
         spatial-temporal applicability.</p>
      {caveat}
    </section>
    """


# ──────────────────────────────────────────────────────────────────
# Scope summary (MNC supplier audit only)
# ──────────────────────────────────────────────────────────────────

def _render_scope_summary(state, sources) -> str:
    """Supplier-focused scope: lists supplier names, AOIs, time windows."""
    blocks = ["<section>", "<h2>Scope Summary</h2>", "<table>"]
    blocks.append(
        "<tr><th>Source</th><th>Centre</th><th>Buffer (km)</th>"
        "<th>Time range</th></tr>"
    )
    for src in sources:
        setup = src.get("screening_setup") or src.get("prioritisation_setup") or {}
        centre = setup.get("centre") or {}
        lat = centre.get("lat")
        lon = centre.get("lon")
        centre_str = (
            f"({lat:.4f}, {lon:.4f})"
            if isinstance(lat, (int, float)) and isinstance(lon, (int, float))
            else "—"
        )
        radius = setup.get("radius_km", "—")
        time_range = setup.get("time_range") or []
        time_str = " → ".join(time_range) if time_range else "—"
        name = html.escape(src.get("name", "Untitled"))
        blocks.append(
            f"<tr><td>{name}</td><td>{centre_str}</td><td>{radius}</td>"
            f"<td>{html.escape(time_str)}</td></tr>"
        )
    blocks.append("</table>")
    blocks.append("</section>")
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Pillar findings (Policy audit)
# ──────────────────────────────────────────────────────────────────

def _render_pillar_findings(state, sources) -> str:
    """One chapter per source — pillar-by-pillar narrative + scores."""
    blocks = ["<section class='chapter-break'>",
              "<h2>Pillar Findings</h2>"]
    for i, src in enumerate(sources):
        if i > 0:
            blocks.append("<div class='chapter-break'></div>")
        blocks.append(_render_source_pillar_block(src))
    blocks.append("</section>")
    return "\n".join(blocks)


# M-P11.2-FIX
def _render_source_pillar_block(src) -> str:
    name = html.escape(src.get("name", "Untitled source"))
    payload = src.get("payload") or {}
    blocks = [f"<h3>{name}</h3>"]

    # M-P11.2-FIX: prioritisation sources don't carry a single
    # screening payload — point readers to the priority section.
    if src.get("type") == "prioritisation":
        blocks.append(
            "<div class='caveat'>"
            "This is a prioritisation source — see the Priority Findings "
            "section for the per-supplier breakdown."
            "</div>"
        )
        return "\n".join(blocks)

    # M-P11.2-FIX: verbal summary requires breadth-of-coverage. If the
    # source didn't run all 19 indicators, skip the prose and show a
    # caveat + pillar-score table instead. Mirrors M-HIDE-SUMMARY on P-05.
    setup = src.get("screening_setup") or {}
    selected = set(setup.get("indicators") or [])
    if selected == set(ALL_INDICATOR_IDS):
        try:
            verbal = generate_verbal_summary(payload)
            paragraphs = [verbal.overview, verbal.air, verbal.ghg, verbal.nature]
        except Exception:  # noqa: BLE001
            paragraphs = ["Verbal summary unavailable for this source."]
        for para in paragraphs:
            if para:
                blocks.append(f"<p>{html.escape(para)}</p>")
    else:
        n_selected = len(selected)
        blocks.append(
            "<div class='caveat'>"
            f"<strong>Partial coverage.</strong> This source ran "
            f"{n_selected} of 19 indicators. A narrative summary is "
            f"shown only for full screenings — the per-pillar score "
            f"table below reflects what was measured."
            "</div>"
        )
        blocks.append(_render_pillar_score_block(payload))

    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Priority findings (MNC supplier audit)
# ──────────────────────────────────────────────────────────────────

def _render_priority_findings(state, sources) -> str:
    """For prioritisation sources: ranked table. For screening sources:
    per-source composite + bands."""
    blocks = ["<section class='chapter-break'>",
              "<h2>Priority Findings</h2>"]
    for src in sources:
        if src.get("type") == "prioritisation":
            blocks.append(_render_prioritisation_table(src))
        else:
            blocks.append(_render_screening_priority_block(src))
    blocks.append("</section>")
    return "\n".join(blocks)


def _render_prioritisation_table(src) -> str:
    name = html.escape(src.get("name", "Untitled prioritisation"))
    supplier_results = src.get("supplier_results", [])
    blocks = [f"<h3>{name}</h3>", "<table>"]
    blocks.append(
        "<tr><th>Supplier</th><th>Status</th>"
        "<th>Air</th><th>GHG</th><th>Nature</th><th>Composite</th></tr>"
    )
    for sup in supplier_results:
        supplier_name = html.escape(sup.get("name", "—"))
        status = html.escape(sup.get("status", "—"))
        result = sup.get("result") or {}
        blocks.append(
            f"<tr><td>{supplier_name}</td><td>{status}</td>"
            f"<td>{_fmt(result.get('air.audit_followup_priority'))}</td>"
            f"<td>{_fmt(result.get('ghg.audit_followup_priority'))}</td>"
            f"<td>{_fmt(result.get('nature.followup_priority'))}</td>"
            f"<td>{_fmt(result.get('composite.overall_screening'))}</td></tr>"
        )
    blocks.append("</table>")
    return "\n".join(blocks)


def _render_screening_priority_block(src) -> str:
    name = html.escape(src.get("name", "Untitled screening"))
    payload = src.get("payload") or {}
    return f"<h3>{name}</h3>" + _render_pillar_score_block(payload)


def _render_pillar_score_block(payload) -> str:
    blocks = ["<table>", "<tr><th>Pillar</th><th>Score</th><th>Band</th></tr>"]
    for label, key in (
        ("Air Pollution",       "air.audit_followup_priority"),
        ("GHG Emissions",       "ghg.audit_followup_priority"),
        ("Nature/Land",         "nature.followup_priority"),
        ("Composite (overall)", "composite.overall_screening"),
    ):
        score = payload.get(key)
        band, band_label = _band_for_score(score)
        score_str = f"{score:.2f}" if isinstance(score, (int, float)) else "—"
        blocks.append(
            f"<tr><td>{label}</td><td>{score_str}</td>"
            f"<td><span class='pillar-chip {band}'>{band_label}</span></td></tr>"
        )
    blocks.append("</table>")
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Indicator detail (Policy audit) — per-source KPI table
# ──────────────────────────────────────────────────────────────────

# M-P11-FIX
def _render_indicator_detail(state, sources) -> str:
    """Policy-audit per-source indicator detail.

    Partial-coverage screening sources already have their pillar score
    table rendered in `pillar_findings` (via the M-P11.2-FIX verbal-
    summary fallback); showing it again here was the visible
    duplication. Full-coverage screenings and prioritisation sources
    are unaffected — for them, `pillar_findings` either shows verbal-
    summary prose (full-19) or a redirect caveat (prioritisation), so
    the table here is genuinely new content.
    """
    full_screening_sources = [
        s for s in sources
        if s.get("type") == "screening"
        and set((s.get("screening_setup") or {}).get("indicators") or [])
            == set(ALL_INDICATOR_IDS)
    ]
    prioritisation_sources = [
        s for s in sources if s.get("type") == "prioritisation"
    ]
    renderable = full_screening_sources + prioritisation_sources
    if not renderable:
        return ""

    blocks = ["<section class='chapter-break'>",
              "<h2>Indicator Detail</h2>"]
    for src in renderable:
        name = html.escape(src.get("name", "Untitled"))
        payload = src.get("payload") or {}
        blocks.append(f"<h3>{name}</h3>")
        blocks.append(_render_pillar_score_block(payload))
    blocks.append("</section>")
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Per-supplier detail (MNC supplier audit)
# ──────────────────────────────────────────────────────────────────

# M-P11.2-FIX
def _render_per_supplier_detail(state, sources) -> str:
    # M-P11.2-FIX: only prioritisation sources contribute to this
    # section. Screening sources are fully covered by priority_findings
    # above — rendering them again here was duplicating the same
    # pillar-score table.
    prioritisation_sources = [
        s for s in sources if s.get("type") == "prioritisation"
    ]
    if not prioritisation_sources:
        return ""

    blocks = ["<section class='chapter-break'>",
              "<h2>Per-Supplier Detail</h2>"]
    for src in prioritisation_sources:
        blocks.append(_render_prioritisation_supplier_breakdown(src))
    blocks.append("</section>")
    return "\n".join(blocks)


def _render_prioritisation_supplier_breakdown(src) -> str:
    """For prioritisation source: one h3 per supplier with their scores."""
    name = html.escape(src.get("name", "Prioritisation"))
    supplier_results = src.get("supplier_results", [])
    blocks = [f"<h3>{name}</h3>"]
    for sup in supplier_results:
        if sup.get("status") in ("failed", "cancelled"):
            continue
        supplier_name = html.escape(sup.get("name", "—"))
        result = sup.get("result") or {}
        blocks.append(f"<h4>{supplier_name}</h4>")
        blocks.append(_render_pillar_score_block(result))
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Reference datasets (M-UI-A6 RD10)
# ──────────────────────────────────────────────────────────────────

# RD10 — disclaimer mirrors the in-app C5 sub-section framing (§4.3) so the
# print report carries the same "context, not scoring" signpost.
_REFERENCE_DATASETS_DISCLAIMER: str = (
    "Reference data context — not part of the composite score. These values "
    "are cumulative or inventory-allocated rather than drawn from the "
    "current screening window."
)

# Audit footnotes — same copy as the C5 cards (RD8 + §4.2), simplified for
# print (the C5 strings live in ui.components.c5_drilldown; kept aligned by
# intent, not import, to avoid an engine/UI cross-dependency in the report
# layer).
_REFERENCE_DATASETS_FOOTNOTE: str = (
    "Hansen contributes to the regional_loss_evidence binary flag in "
    "External Driver Screening but is not part of the composite score. "
    "ODIAC is an inventory-allocated dataset, not an atmospheric "
    "measurement, and is not used in the composite score."
)


def _render_reference_dataset_block(payload) -> str:
    """One reference-dataset table for a single screening payload.

    Mirrors the C5 cards' headline metrics (Hansen cumulative loss %, ODIAC
    annual emissions intensity), with the same RD12 "Data not available"
    fallback when a value is missing.
    """
    loss_pct = payload.get("nature.forest_loss.pct")
    co2_mean = payload.get("ghg.co2.mean")
    hansen_val = (
        f"{loss_pct:.2f}% of buffer area lost (5-year cumulative)"
        if loss_pct is not None else "Data not available for this AOI"
    )
    odiac_val = (
        f"{co2_mean:,.0f} t CO₂ yr⁻¹ per pixel "
        "(annual emissions intensity)"
        if co2_mean is not None else "Data not available for this AOI"
    )
    return "\n".join([
        "<table>",
        "<tr><th>Reference dataset</th><th>Value</th><th>Source</th></tr>",
        f"<tr><td>Hansen forest loss</td><td>{html.escape(hansen_val)}</td>"
        "<td>Hansen Global Forest Change (University of Maryland)</td></tr>",
        f"<tr><td>ODIAC CO₂</td><td>{html.escape(odiac_val)}</td>"
        "<td>ODIAC fossil-fuel CO₂ (NIES, Japan)</td></tr>",
        "</table>",
        f"<p><em>{html.escape(_REFERENCE_DATASETS_FOOTNOTE)}</em></p>",
    ])


def _render_reference_datasets(state, sources) -> str:
    """RD10 — reference-dataset context section for the PDF report.

    Appears after the scored-indicators section. Renders the Hansen + ODIAC
    reference values per screening source, marked clearly as context rather
    than scoring. Returns "" (section omitted) when no screening source is
    present — e.g. a pure-prioritisation report carries no per-AOI payload.
    """
    screening_sources = [s for s in sources if s.get("type") == "screening"]
    if not screening_sources:
        return ""
    blocks = [
        "<section class='chapter-break'>",
        "<h2>Reference datasets</h2>",
        f"<p><em>{html.escape(_REFERENCE_DATASETS_DISCLAIMER)}</em></p>",
    ]
    for src in screening_sources:
        name = html.escape(src.get("name", "Untitled"))
        payload = src.get("payload") or {}
        blocks.append(f"<h3>{name}</h3>")
        blocks.append(_render_reference_dataset_block(payload))
    blocks.append("</section>")
    return "\n".join(blocks)


# ──────────────────────────────────────────────────────────────────
# Trend graph (M-TREND-A2 / UT10)
# ──────────────────────────────────────────────────────────────────

def _render_trend_graph(state, sources) -> str:
    """Per-indicator trend graphs for any saved trend records in the report.

    Emits one block per ``type=="trend"`` source: an inline SVG of the trend
    graph (scatter + Theil–Sen line; season bands when flagged) generated from
    the saved per-day series, plus a short prose verdict + the metrics.
    Returns "" (section omitted) when no trend sources are present.

    Graceful fallback (UT10 / §8): if SVG generation fails for a record, that
    record's block degrades to a statistics summary + a series table rather
    than breaking the section — consistent with the assembler's per-section
    try/except.
    """
    trend_sources = [s for s in sources if s.get("type") == "trend"]
    if not trend_sources:
        return ""
    blocks = [
        "<section class='chapter-break'>",
        "<h2>Trend analysis</h2>",
        "<p><em>Per-indicator trend drill-downs (Theil–Sen slope + "
        "Mann–Kendall significance over the screening window). Trend is a "
        "drill-down signal — it does not enter the composite screening "
        "score.</em></p>",
    ]
    for src in trend_sources:
        name = html.escape(src.get("display_name") or src.get("indicator_id") or "Trend")
        result = src.get("trend_result") or {}
        setup = src.get("screening_setup") or {}
        lat = (setup.get("centre") or {}).get("lat")
        blocks.append(f"<h3>{name}</h3>")
        blocks.append(_render_one_trend_block(result, lat, name))
    blocks.append("</section>")
    return "\n".join(blocks)


def _render_one_trend_block(result: dict, lat, name: str = "") -> str:
    """One trend record → verdict + metrics + inline SVG, with a table
    fallback if the SVG build raises."""
    badge = verdict_badge(result)
    conf = result.get("trend_confidence")
    conf_str = "—" if conf is None else f"{conf:.2f}"
    metrics = (
        f"<p><strong>{html.escape(badge['text'])}</strong></p>"
        f"<ul>"
        f"<li>Significance: {html.escape(significance_text(result))}</li>"
        f"<li>Trend confidence: {conf_str}</li>"
        f"<li>Raw slope: {html.escape(slope_display(result))}</li>"
        f"</ul>"
    )
    try:
        seasonal = bool(result.get("seasonal_flag"))
        svg = build_trend_svg(
            result, lat=lat, show_season_bands=seasonal, width=680,
            y_label=name or "Site value",
            title=f"{name} — daily site value" if name else None,
        )
        return metrics + f"<div class='trend-graph'>{svg}</div>"
    except Exception as exc:  # noqa: BLE001 — never emit a broken section
        return metrics + _render_trend_series_table(result, str(exc))


def _render_trend_series_table(result: dict, error: str) -> str:
    """Fallback when SVG generation fails: the per-day series as a table."""
    rows = [
        f"<tr><td>{html.escape(str(iso))}</td><td>{html.escape(f'{v:.4g}')}</td></tr>"
        for iso, v in (result.get("series") or [])
    ]
    return (
        f"<p><em>Graph unavailable ({html.escape(error)}); showing the "
        f"per-day series.</em></p>"
        "<table class='series-table'><thead><tr><th>Date</th>"
        "<th>Value</th></tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>"
    )


# ──────────────────────────────────────────────────────────────────
# Provenance appendix
# ──────────────────────────────────────────────────────────────────

def _render_provenance_appendix(state, sources) -> str:
    blocks = ["<section class='chapter-break'>",
              "<h2>Provenance Appendix</h2>",
              "<p>Reference assets, computation scales, and time "
              "windows for every indicator that returned data in "
              "this report's sources.</p>"]
    for src in sources:
        name = html.escape(src.get("name", "Source"))
        blocks.append(f"<h3>{name}</h3>")
        payload = src.get("payload") or {}
        blocks.append(_render_provenance_for_payload(payload))
    blocks.append("</section>")
    return "\n".join(blocks)


def _render_provenance_for_payload(payload) -> str:
    prov_blocks = [
        (key.removeprefix("_provenance."), val)
        for key, val in payload.items()
        if isinstance(key, str) and key.startswith("_provenance.")
        and isinstance(val, dict)
    ]
    if not prov_blocks:
        return "<p>No provenance entries.</p>"
    blocks = ["<table>",
              "<tr><th>Indicator</th><th>Asset</th><th>Scale (m)</th>"
              "<th>Time range</th><th>Status</th></tr>"]
    for ind_id, prov in sorted(prov_blocks):
        asset = html.escape(str(prov.get("asset_id", "—")))
        scale = prov.get("native_scale_m", "—")
        time_range = prov.get("time_range") or []
        time_str = " → ".join(time_range) if time_range else "—"
        status = "Skipped" if prov.get("skipped_reason") else "OK"
        blocks.append(
            f"<tr><td>{html.escape(ind_id)}</td><td>{asset}</td>"
            f"<td>{scale}</td><td>{html.escape(time_str)}</td>"
            f"<td>{status}</td></tr>"
        )
    blocks.append("</table>")

    # M-UI-A1-SURFACE Sub-milestone 3 (24 May 2026): per-indicator
    # audit-transparency extras (n_valid_dates, granule_count, …).
    # confidence_terms is deliberately excluded — it has its own
    # dedicated surface in the P-05 C5 "What's behind this confidence?"
    # expander, not in the report appendix. Do NOT "fix" this exclusion
    # without re-reading the M-UI-A1-SURFACE spec §3 sub-milestone 3.
    extras_html = _render_provenance_extras(prov_blocks)
    if extras_html:
        blocks.append(extras_html)
    # M-TIER-A3 Step H2 — coastal handling sub-block. Renders only when
    # at least one indicator's ring touched water; reuses Surface 1's
    # copy template for consistency with the P-05 C5 expander.
    coastal_html = _render_coastal_handling_appendix(prov_blocks)
    if coastal_html:
        blocks.append(coastal_html)
    # M-FALLBACK-A1 §5.5 — "Fallback applied" sub-block. Renders only when
    # at least one indicator used the SPPY or climatology fallback; omitted
    # entirely otherwise (§7.11).
    fallback_html = _render_fallback_appendix(prov_blocks)
    if fallback_html:
        blocks.append(fallback_html)
    # M-ATTRIB-A1 §5.6 — habitat attribution context. Low-only; omitted
    # entirely otherwise (parallels coastal / fallback sub-blocks).
    habitat_attrib_html = _render_habitat_attribution_appendix(prov_blocks)
    if habitat_attrib_html:
        blocks.append(habitat_attrib_html)
    # M-WIND-A1 v2.0 §6.4 — wind attribution context. Low-only (WA20);
    # supplier with no Low-wind indicators gets no section. Lists each
    # affected indicator with its mean wind speed and asymmetry ratio.
    wind_attrib_html = _render_wind_attribution_appendix(prov_blocks)
    if wind_attrib_html:
        blocks.append(wind_attrib_html)
    return "\n".join(blocks)


# M-TIER-A3 Step H2 — copy mirrors the C5 expander Surface 1 template
# (kept in sync by string match in `tests/test_coastal_handling_surfaces.py`).
_COASTAL_HANDLING_APPENDIX_HEADER: str = "Coastal AOI handling"
_COASTAL_HANDLING_APPENDIX_INTRO: str = (
    "One or more indicators in this report ran against a background ring "
    "that partly overlapped the coastline. The tool applied a global land "
    "mask (MODIS MOD44W v6, 250 m) to exclude ocean pixels from the "
    "baseline reduction — the median + σ comparison was computed against "
    "the terrestrial portion of the ring only. Without this adjustment, "
    "ocean pixels (which have near-zero pollution and would otherwise "
    "average in as \"clean background\") would artificially depress the "
    "baseline and inflate the supplier's anomaly score. The land-only "
    "baseline gives a more honest comparison against the surrounding "
    "terrestrial area."
)


def _render_coastal_handling_appendix(
    prov_blocks: list[tuple[str, dict]],
) -> str:
    """Render a coastal-AOI-handling sub-block when any indicator's
    background ring was partly over water (spec H2 PDF surface).

    Iterates the report's provenance blocks once. For each indicator
    whose `extra.ring_land_fraction < 1.0` and `extra.land_mask_applied`
    is truthy, surface a row showing the geometric land fraction. If
    *no* indicator hit the coastline, omit the section entirely so the
    PDF doesn't carry a misleading "this is a coastal site" heading
    for a fully inland AOI.
    """
    rows: list[str] = []
    any_below_warning_threshold = False
    for ind_id, prov in sorted(prov_blocks):
        extra = prov.get("extra")
        if not isinstance(extra, dict):
            continue
        land_fraction = extra.get("ring_land_fraction")
        if not isinstance(land_fraction, (int, float)):
            continue
        if land_fraction >= 1.0:
            continue
        if extra.get("land_mask_applied") is False:
            continue
        water_pct = max(0, min(100, round((1.0 - float(land_fraction)) * 100)))
        land_pct  = 100 - water_pct
        rows.append(
            f"<li><strong>{html.escape(ind_id)}</strong> — "
            f"{land_pct}% land / {water_pct}% water</li>"
        )
        # Warning band threshold matches the C5 expander Surface 1.
        if land_fraction < 0.20:
            any_below_warning_threshold = True
    if not rows:
        return ""
    parts = [
        f"<h4>{_COASTAL_HANDLING_APPENDIX_HEADER}</h4>",
        f"<p>{_COASTAL_HANDLING_APPENDIX_INTRO}</p>",
        "<ul class='provenance-extras'>",
        "\n".join(rows),
        "</ul>",
    ]
    if any_below_warning_threshold:
        parts.append(
            "<p><em>At least one indicator's comparison area is mostly "
            "water; the baseline is computed from a small land area and "
            "should be interpreted with care.</em></p>"
        )
    return "\n".join(parts)


# M-FALLBACK-A1 §5.5 — PDF audit-transparency "Fallback applied" sub-block.
# Surfaces the same fallback facts the in-app C5 expander shows, persisted in
# the auditor's exportable artefact.
_FALLBACK_APPENDIX_HEADER: str = "Fallback methodology applied"
_FALLBACK_APPENDIX_INTRO: str = (
    "One or more indicators in this report could not be computed from "
    "current-window satellite data and used a documented fallback. Each "
    "substitution carries a reduced confidence score (year-old data ×0.60; "
    "regional baseline ×0.75). The substitutions are listed below for audit "
    "transparency."
)


def _render_fallback_appendix(prov_blocks: list[tuple[str, dict]]) -> str:
    """Render the §5.5 fallback sub-block, or "" when no fallback fired.

    Lists per-indicator temporal (SPPY / sliding-lookback) and climatology
    substitutions, plus the AOI scale class when it's larger than site-scale.
    """
    temporal_rows: list[str] = []
    climatology_rows: list[str] = []
    scale_class: str | None = None

    for ind_id, prov in sorted(prov_blocks):
        extra = prov.get("extra")
        if not isinstance(extra, dict):
            continue
        if scale_class is None:
            sc = extra.get("aoi_scale_class")
            if sc in ("regional", "biome"):
                scale_class = sc
        if extra.get("temporal_fallback_used"):
            strategy = extra.get("temporal_fallback_strategy")
            window = extra.get("temporal_fallback_source_window") or "an earlier period"
            window = window.replace("/", " to ")
            label = (
                "earlier-window data"
                if strategy == "sliding_lookback"
                else "same-period-previous-year data"
            )
            temporal_rows.append(
                f"<li><strong>{html.escape(ind_id)}</strong> — {label} "
                f"({html.escape(window)}) due to sparse current-window coverage</li>"
            )
        if extra.get("climatology_fallback_used"):
            vintage = html.escape(str(extra.get("climatology_fallback_vintage") or "latest"))
            climatology_rows.append(
                f"<li><strong>{html.escape(ind_id)}</strong> — regional baseline "
                f"(country median, {vintage} vintage) due to sparse ring coverage</li>"
            )

    if not temporal_rows and not climatology_rows:
        return ""

    parts = [
        f"<h4>{_FALLBACK_APPENDIX_HEADER}</h4>",
        f"<p>{_FALLBACK_APPENDIX_INTRO}</p>",
        "<ul class='provenance-extras'>",
        *temporal_rows,
        *climatology_rows,
        "</ul>",
    ]
    if scale_class is not None:
        parts.append(
            f"<p>AOI scale class: <strong>{html.escape(scale_class)}</strong> "
            f"— background comparisons reflect regional-scale context.</p>"
        )
    return "\n".join(parts)


# M-ATTRIB-A1 §5.6 — PDF "Habitat attribution context" sub-block. Low-only,
# parallel to the coastal / fallback sub-blocks. Surfaces the supplier→change
# centroid offset for auditors when habitat conversion attributability is Low.
_HABITAT_ATTRIB_APPENDIX_HEADER: str = "Habitat attribution context"


def _render_habitat_attribution_appendix(
    prov_blocks: list[tuple[str, dict]],
) -> str:
    """Render the §5.6 habitat-attribution sub-block, or "" unless Low.

    Reads `extra.spatial_link_terms` from the
    `nature.supplier_spatial_link` provenance block. Fires only when the
    attributability state is "low" (High / Moderate / Sparse surface on the
    map, not in the report); omitted entirely otherwise.
    """
    for ind_id, prov in prov_blocks:
        if ind_id != "nature.supplier_spatial_link":
            continue
        extra = prov.get("extra")
        if not isinstance(extra, dict):
            continue
        terms = extra.get("spatial_link_terms")
        if not isinstance(terms, dict):
            continue
        if terms.get("attributability_state") != "low":
            return ""
        offset = terms.get("centroid_offset_km")
        dist = f"{offset:.1f} km" if isinstance(offset, (int, float)) else "—"
        direction = terms.get("direction") or "—"
        n_change = terms.get("n_change_pixels") or 0
        return "\n".join([
            f"<h4>{_HABITAT_ATTRIB_APPENDIX_HEADER}</h4>",
            "<p>This supplier shows <strong>Low</strong> attribution "
            "confidence on habitat conversion:</p>",
            "<ul class='provenance-extras'>",
            f"<li>Centroid of habitat changes: <strong>{dist}</strong> from "
            f"supplier ({html.escape(str(direction))} direction)</li>",
            f"<li>N = <strong>{int(n_change)}</strong> change pixels</li>",
            "<li>Interpretation: detected changes are spatially concentrated "
            "away from the supplier coordinate.</li>",
            "</ul>",
        ])
    return ""


# M-WIND-A1 v2.0 §6.4 — PDF "Wind attribution context" sub-block. Low-only,
# parallel to coastal / fallback / habitat-attribution sub-blocks. Lists each
# in-scope Air indicator whose wind attributability fired Low so auditors see
# exactly which signals carry an upwind-transport caveat.
_WIND_ATTRIB_APPENDIX_HEADER: str = "Wind attribution context"

_WIND_ATTRIB_APPENDIX_INTRO: str = (
    "This supplier shows <strong>Low</strong> attribution confidence on the "
    "following indicators due to wind conditions during anomaly days. Strong "
    "winds and asymmetric upwind/downwind background values suggest the "
    "observed anomalies may reflect transported pollution from external "
    "sources rather than (or in addition to) the supplier itself."
)


def _render_wind_attribution_appendix(
    prov_blocks: list[tuple[str, dict]],
) -> str:
    """Render the §6.4 wind-attribution sub-block, or "" when no Low fired.

    Iterates the report's provenance blocks once. For each in-scope Air
    indicator (NO₂, SO₂, HCHO, AAI, AOD) whose
    ``extra.wind_attributability_state == "low"``, surface a row with the
    mean wind speed, asymmetry ratio, and the wind data window. Moderate
    and High indicators surface visually on the map (not in the PDF, per
    WA20); supplier with no Low-wind indicators gets no section at all.
    """
    rows: list[str] = []
    for ind_id, prov in sorted(prov_blocks):
        extra = prov.get("extra")
        if not isinstance(extra, dict):
            continue
        if extra.get("wind_attributability_state") != "low":
            continue
        speed = extra.get("wind_mean_speed_ms")
        ratio = extra.get("wind_mean_asymmetry_ratio")
        window = extra.get("wind_data_window") or ""
        window_str = (
            window.replace("/", " to ") if isinstance(window, str) and "/" in window
            else "—"
        )
        if isinstance(ratio, (int, float)):
            metrics_str = (
                f"Mean wind <strong>{speed:.1f} m/s</strong>, asymmetry ratio "
                f"<strong>{ratio:.2f}</strong>"
            ) if isinstance(speed, (int, float)) else (
                f"Asymmetry ratio <strong>{ratio:.2f}</strong>"
            )
        else:
            metrics_str = (
                f"Mean wind <strong>{speed:.1f} m/s</strong> (all anomaly days calm)"
                if isinstance(speed, (int, float)) else "wind metrics unavailable"
            )
        rows.append(
            f"<li><strong>{html.escape(ind_id)}</strong> — {metrics_str} "
            f"({html.escape(window_str)})<br/>"
            f"<em>Low attribution confidence — wind conditions suggest "
            f"external sources may have contributed.</em></li>"
        )
    if not rows:
        return ""
    return "\n".join([
        f"<h4>{_WIND_ATTRIB_APPENDIX_HEADER}</h4>",
        f"<p>{_WIND_ATTRIB_APPENDIX_INTRO}</p>",
        "<ul class='provenance-extras'>",
        "\n".join(rows),
        "</ul>",
    ])


# M-UI-A1-SURFACE Sub-milestone 3 polish (24 May 2026): the PDF
# audience is business / audit-reviewer-facing and benefits from a
# narrow, narrative surface. Engineering calibration parameters
# (aod_qa_bit_mask, distance_decay_km, conversion_saturation_pct,
# ndvi_negative_trend_threshold, baseline_*, ring/buffer_loss_rate_*,
# hansen_max_loss_year, lookback_years, ratio_threshold, etc.) belong
# in the CSV export (which already carries them as dedicated columns);
# the PDF appendix surfaces only the multi-swath dates-vs-granules
# story the M-TIER-A1 close-entry promised. confidence_terms is
# still excluded — that surface lives in the P-05 C5 "What's behind
# this confidence?" expander.
_PDF_AUDIT_TRANSPARENCY_KEYS: frozenset[str] = frozenset({
    "n_valid_dates",
    "granule_count",
})


def _render_provenance_extras(prov_blocks: list[tuple[str, dict]]) -> str:
    """Build the per-indicator audit-transparency sub-block.

    Renders as English prose, one bullet per indicator where
    ``granule_count > n_valid_dates`` (multi-swath products like
    MAIAC AOD at ~58 granules/day, S5P L3 CH4 at ~14×). Single-image-
    per-day products (NO2, SO2, CO, HCHO, O3, AAI, PM2.5, PM10, NDVI,
    VIIRS) have ``granule_count == n_valid_dates`` and would tell no
    story — they're omitted.

    The entire section is omitted when no indicator has multi-swath
    divergence (e.g. pre-engine-fix payloads with no extras, or
    payloads with only single-image-per-day products) so the PDF
    doesn't carry a dangling empty heading.

    Allowlist enforcement: only ``_PDF_AUDIT_TRANSPARENCY_KEYS`` are
    read from ``provenance.extra``. See that constant's comment for
    the boundary rationale.
    """
    rows: list[str] = []
    for ind_id, prov in sorted(prov_blocks):
        extra = prov.get("extra")
        if not isinstance(extra, dict):
            continue
        # Read only the allowlisted keys; everything else is engineering
        # calibration that belongs in the CSV, not the PDF appendix.
        n_valid_dates = extra.get("n_valid_dates")
        granule_count = extra.get("granule_count")
        if not isinstance(n_valid_dates, int) or not isinstance(granule_count, int):
            continue
        if granule_count <= n_valid_dates:
            continue  # single-image-per-day — no audit story to tell.
        rows.append(
            f"<li><strong>{html.escape(ind_id)}</strong> — "
            f"{n_valid_dates:,} distinct dates observed across "
            f"{granule_count:,} raw images</li>"
        )
    if not rows:
        return ""
    return (
        "<h4>Audit-transparency extras</h4>\n"
        "<p><em>Multi-swath satellite indicators, showing distinct "
        "observation dates vs raw image counts processed.</em></p>\n"
        "<ul class='provenance-extras'>\n"
        + "\n".join(rows)
        + "\n</ul>\n"
        "<p><em>Per-indicator engineering parameters are available "
        "in the CSV export.</em></p>"
    )


# ──────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────

def _composite_score(src) -> float | None:
    """Pull composite from screening payload or prioritisation summary."""
    if src.get("type") == "screening":
        value = (src.get("payload") or {}).get("composite.overall_screening")
        return value if isinstance(value, (int, float)) else None
    if src.get("type") == "prioritisation":
        # Use mean across plottable suppliers as a quick summary.
        results = src.get("supplier_results", [])
        scores = []
        for r in results:
            if r.get("status") not in ("success", "partial"):
                continue
            value = (r.get("result") or {}).get("composite.overall_screening")
            if isinstance(value, (int, float)):
                scores.append(value)
        return sum(scores) / len(scores) if scores else None
    return None


def _band_for_score(score: float | None) -> tuple[str, str]:
    """Return (css_class, human_label)."""
    if not isinstance(score, (int, float)):
        return "grey", "No data"
    low, high = TRAFFIC_LIGHT_THRESHOLDS
    if score >= high:
        return "red", "High priority"
    if score >= low:
        return "amber", "Moderate"
    return "green", "Low priority"


def _count_indicators_run(src) -> int | None:
    setup = src.get("screening_setup") or src.get("prioritisation_setup") or {}
    indicators = setup.get("indicators") or []
    return len(indicators) if indicators else None


def _fmt(value) -> str:
    if value is None:
        return "—"
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "—"


# ──────────────────────────────────────────────────────────────────
# Registry
# ──────────────────────────────────────────────────────────────────

_SECTION_REGISTRY: dict[str, Callable] = {
    "title_page":            _render_title_page,
    "executive_summary":     _render_executive_summary,
    "methodology":           _render_methodology,
    "scope_summary":         _render_scope_summary,
    "pillar_findings":       _render_pillar_findings,
    "priority_findings":     _render_priority_findings,
    "indicator_detail":      _render_indicator_detail,
    "per_supplier_detail":   _render_per_supplier_detail,
    "trend_graph":           _render_trend_graph,
    "reference_datasets":    _render_reference_datasets,
    "provenance_appendix":   _render_provenance_appendix,
}
